sudo: false
language: python
python:
    - '2.6'
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
    - 'pypy'
    - 'pypy3'

before_install:
    - wheel version

# command to install dependencies
install:
    - pip install -r test_requirements.txt
    - pip install -e .
    - pip install coveralls

# command to run tests
script:
    - python setup.py test

after_success:
    - coveralls
    - python setup.py bdist_wheel
    - ls -la dist/
